/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_liujianwj_jnisimplydemo_JniUtils */

#ifndef _Included_com_github_liujianwj_jnisimplydemo_JniUtils
#define _Included_com_github_liujianwj_jnisimplydemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_liujianwj_jnisimplydemo_JniUtils
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_liujianwj_jnisimplydemo_JniUtils_getNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
